### ISSUE TITLE
Not picking up ansible.cfg settings

### ISSUE THREAD

**Issue by wbagdon** [ujenmr/ansible-logstash-callback#10]
I've set the options in `ansible.cfg` like in the examples in `logstash.py` but only the env vars seem to be picked up.

This does not work:
```
[defaults]
callback_whitelist = logstash

[callback_logstash]
server = logstash
port = 5000
pre_command = git rev-parse HEAD
type = enterprise
```

But if I set the environment vars, then it works.
Am I mis-configuring something in the `ansible.cfg`?
I'm trying to make these settings portable so that other users will also log out to logstash.

**Comment by wbagdon** [comment]
Looks like the documentation just needs to be updated, I've created a PR #11

**Comment by ujenmr** [comment]
seems module need to update, just copy file logstash.py to ~/.ansible/plugins/callback/

**Comment by ujenmr** [comment]
ansible 2.7.1 still use old version of module

**Comment by ujenmr** [comment]
https://github.com/ansible/ansible/pull/20725
