### ISSUE TITLE
Ansible version that runs the playbook is not logged

### ISSUE THREAD

**Issue by pgporada** [ujenmr/ansible-logstash-callback#5]
It would be useful to see the version of ansible in each log message. I have a testing situation with different versions of ansible and would like to see if anything changes between these different versions.

Expected output would be something like 
```
{
        "ansible_type" => "start",
               "level" => "INFO",
             "session" => "87c7bf9e-f731-11e6-845a-2477032230c8",
             "message" => "START /tmp/kitchen/default.yml",
                "type" => "ansible",
    "ansible_playbook" => "/tmp/kitchen/default.yml",
    "ansible_version" => "2.2.1.0",                     <==========================
                "tags" => [],
                "path" => "/tmp/kitchen/callback_plugins/logstash.py",
          "@timestamp" => 2017-02-20T05:57:58.497Z,
                "port" => 43622,
            "@version" => "1",
                "host" => "laptappy",
         "logger_name" => "python-logstash-logger",
              "status" => "OK"
}
```

My particular setup utilizes the tox project for testing roles/playbooks as follows

`tox.ini`
```
[tox]
minversion = 1.8
envlist = py{27}-ansible{221,220,212,202}
skipsdist = true

[flake8]
ignore = E501

[testenv]
passenv = *
deps =
    python-vagrant
    molecule
    ansible202: ansible==2.0.2.0
    ansible212: ansible==2.1.2.0
    ansible220: ansible==2.2.0.0
    ansible221: ansible==2.2.1.0
commands =
    molecule converge
    molecule verify
```

This setup, for me, would run a virtualenv in Python 2.7 for Ansible 2.0.2.0, Ansible 2.1.2.0 etc, and run the shell commands `molecule converge` and `molecule verify`. Being able to get this data into my logstash/elasticsearch would be really helpful.

**Comment by ujenmr** [comment]
As solution you can use the new parameter ```LOGSTASH_PRE_COMMAND (optional): defaults is "ansible --version | head -1" execute command before run and result put ansible_pre_command_output field```

**Comment by pgporada** [comment]
That works for me.
